"""empty message

Revision ID: ce6760b2cba5
Revises: 675b29ff1da1
Create Date: 2025-10-19 00:33:24.339920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce6760b2cba5'
down_revision: Union[str, Sequence[str], None] = '675b29ff1da1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lands',
    sa.Column('number', sa.String(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('area', sa.Float(), nullable=False),
    sa.Column('property_type', sa.String(), nullable=False),
    sa.Column('usage', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leaders',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('adres', sa.Column('year', sa.Integer(), nullable=False))
    op.alter_column('companies', 'inn',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.drop_column('companies', 'year')
    op.add_column('investments', sa.Column('year', sa.Integer(), nullable=False))
    op.add_column('profits', sa.Column('year', sa.Integer(), nullable=False))
    op.add_column('revenues', sa.Column('year', sa.Integer(), nullable=False))
    op.add_column('staff', sa.Column('year', sa.Integer(), nullable=False))
    op.add_column('tax', sa.Column('year', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tax', 'year')
    op.drop_column('staff', 'year')
    op.drop_column('revenues', 'year')
    op.drop_column('profits', 'year')
    op.drop_column('investments', 'year')
    op.add_column('companies', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('companies', 'inn',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('adres', 'year')
    op.drop_table('leaders')
    op.drop_table('lands')
    # ### end Alembic commands ###
